analyzer:
  errors:
    avoid_catches_without_on_clauses: ignore
    flutter_style_todos: ignore
    avoid_redundant_argument_values: ignore
    unused_element: ignore

linter:
  rules:
    public_member_api_docs: false
